site_name: ChamberForge Documentation
site_dir: ../cfdocs/
nav:
- Home: index.md
- Group: group.md
- Organization: organization.md
- Reporting: reporting.md
- API: api.md
theme: material
markdown_extensions:
  - extra