site_name: ''
site_dir: ../cfdocs/
nav:
- Home: index.md
- Group: group.md
- Organization: organization.md
- Reporting: reporting.md
- API: api.md
theme: 
  name: 'material'
  logo: 'images/cf-logo.png'
  custom_dir: 'materialcustom/'
  favicon: 'images/favicon.ico'
extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/chamberforge/'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCaN5kSbbMWcMU4Nwk9ufSbA'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/chamberforge'
markdown_extensions:
  - extra